description = "Cleanup"

prompt = """
double check if you have implemented the specification as intended.\ 
clean up dead & old codes.\
check if there in any overengineering.\
check if Testing code covers overall > 80%
commit, push, pr
"""